// <auto-generated />
namespace PomStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MasterData01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MasterData01));
        
        string IMigrationMetadata.Id
        {
            get { return "201512291627572_MasterData0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
